version: "3.8"

services:
  postgres:
    image: postgres:13.3
    networks:
      - backend
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: backend
    volumes:
      - ./.docker/postgres:/docker-entrypoint-initdb.d
    command:
      - postgres
      - -c
      - max_connections=1000
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  trades-api:
    image: "local/trades:local"
    build:
      context: .
    env_file:
      - .env.trades
    restart: unless-stopped
    networks:
      - backend
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8081:8080"

  poller:
    image: "local/poll:local"
    build:
      context: .
    env_file:
      - .env.poll
    restart: unless-stopped
    networks:
      - backend

    volumes:
      - type: volume
        source: trades
        target: /examples
        volume:
          nocopy: true
networks:
  backend:
    name: backend

volumes:
  trades: